name: Scan for CVEs

permissions:
  contents: read

on:
  schedule:
    - cron: "0 10 * * *"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"

jobs:
  scan-cves:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan Repo
        id: scan
        uses: anchore/scan-action@v3
        with:
            path: "."
            severity-cutoff: "high"
            output-format: "sarif"

      - name: Upload Scan Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

# If you need to see scan results in runner's console          
      # - name: Inspect Scan Results
      #   run: cat ${{ steps.scan.outputs.sarif }}